In [ ]:
!pip install groq

Collecting groq
  Downloading groq-1.0.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-1.0.0-py3-none-any.whl (138 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.3/138.3 kB 4.3 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-1.0.0

In [ ]:
!pip install pandas openai

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!pip install groq
from groq import Groq
import os

os.environ["GROQ_API_KEY"] = "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"
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

Requirement already satisfied: groq in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)

In [ ]:
import pandas as pd
from groq import Groq

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

In [ ]:
from google.colab import files
import pandas as pd

# Upload CSV file
uploaded = files.upload()
# Gets the uploaded file name
file_name = list(uploaded.keys())[0]

# Loads the uploaded file into pandas DataFrame
# Using pd.read_excel because the uploaded file has an .xlsx extension
df = pd.read_excel(file_name)

# Displays first few rows
df.head()

Saving first try.csv.xlsx to first try.csv (3).xlsx

,Unnamed: 0,NAME OF THE STUDENT,UNIVERSITY,PROGRAM NAME,Specialisation,SEMESTER,Domain,GENERAL MANAGEMENT SCORE (OUT of 50),Domain Specific SCORE (OUT 50),TOTAL SCORE (OUT of 100),RANK,PERCENTILE
0,0,Camila Wood,"Stanford University, USA",B.Com,Honours,5th,Finance,50,50,100.0,1,1.000000
1,1,Alexander Thompson,"Stanford University, USA",B.Com,Financial Services,5th,Finance,50,50,100.0,2,0.993377
2,2,Liam Taylor,"Harvard University, USA",B.Com,Accounting Analytics,5th,BA,50,50,100.0,3,0.986755
3,3,Evelyn Jenkins,"Stanford University, USA",B.Com,Honours,5th,Finance,49,50,99.0,4,0.980132
4,4,Michael Jackson,"Harvard University, USA",MBA,International Business,3rd,IB,50,49,99.0,5,NaN

In [ ]:
# 1. Remove unnecessary index column if it exists
if "Unnamed: 0" in df.columns:
    df = df.drop(columns=["Unnamed: 0"])

# 2. Drop rows where critical score values are missing
clean_df = df.dropna(subset=[
    "GENERAL MANAGEMENT SCORE (OUT of 50)",
    "Domain Specific SCORE (OUT 50)"
])

# 3. Convert score columns to numeric (safety step)
clean_df["GENERAL MANAGEMENT SCORE (OUT of 50)"] = pd.to_numeric(
    clean_df["GENERAL MANAGEMENT SCORE (OUT of 50)"]
)

clean_df["Domain Specific SCORE (OUT 50)"] = pd.to_numeric(
    clean_df["Domain Specific SCORE (OUT 50)"]
)

# 4. Recalculate TOTAL SCORE to show transformation logic
clean_df["CALCULATED TOTAL SCORE"] = (
    clean_df["GENERAL MANAGEMENT SCORE (OUT of 50)"] +
    clean_df["Domain Specific SCORE (OUT 50)"]
)

# 5. Create a performance category (business logic)
def performance_label(score):
    if score >= 90:
        return "Excellent"
    elif score >= 75:
        return "Good"
    else:
        return "Average"

clean_df["PERFORMANCE CATEGORY"] = clean_df["CALCULATED TOTAL SCORE"].apply(performance_label)

# Show final cleaned data
clean_df.head()

,NAME OF THE STUDENT,UNIVERSITY,PROGRAM NAME,Specialisation,SEMESTER,Domain,GENERAL MANAGEMENT SCORE (OUT of 50),Domain Specific SCORE (OUT 50),TOTAL SCORE (OUT of 100),RANK,PERCENTILE,CALCULATED TOTAL SCORE,PERFORMANCE CATEGORY
0,Camila Wood,"Stanford University, USA",B.Com,Honours,5th,Finance,50,50,100.0,1,1.000000,100,Excellent
1,Alexander Thompson,"Stanford University, USA",B.Com,Financial Services,5th,Finance,50,50,100.0,2,0.993377,100,Excellent
2,Liam Taylor,"Harvard University, USA",B.Com,Accounting Analytics,5th,BA,50,50,100.0,3,0.986755,100,Excellent
3,Evelyn Jenkins,"Stanford University, USA",B.Com,Honours,5th,Finance,49,50,99.0,4,0.980132,99,Excellent
4,Michael Jackson,"Harvard University, USA",MBA,International Business,3rd,IB,50,49,99.0,5,NaN,99,Excellent

In [ ]:
pipeline_code = f"""
Dataset Description:
The dataset contains student academic evaluation details with the following columns:
{', '.join(df.columns)}

Pipeline Logic:
1. Load the CSV dataset containing student evaluation details.
2. Remove rows where critical score columns are missing:
   - GENERAL MANAGEMENT SCORE (OUT of 50)
   - Domain Specific SCORE (OUT 50)
3. Convert score columns to numeric format.
4. Recalculate total score as:
   GENERAL MANAGEMENT SCORE (OUT of 50) + Domain Specific SCORE (OUT 50)
5. Create a new column called PERFORMANCE CATEGORY:
   - Excellent: total score >= 90
   - Good: total score >= 75
   - Average: total score < 75
6. Output the cleaned and transformed dataset.
"""
print(pipeline_code)

Dataset Description:
The dataset contains student academic evaluation details with the following columns:
NAME OF THE STUDENT, UNIVERSITY, PROGRAM NAME, Specialisation, SEMESTER, Domain, GENERAL MANAGEMENT SCORE (OUT of 50), Domain Specific SCORE (OUT 50), TOTAL SCORE (OUT of 100), RANK, PERCENTILE

Pipeline Logic:
1. Load the CSV dataset containing student evaluation details.
2. Remove rows where critical score columns are missing:
   - GENERAL MANAGEMENT SCORE (OUT of 50)
   - Domain Specific SCORE (OUT 50)
3. Convert score columns to numeric format.
4. Recalculate total score as:
   GENERAL MANAGEMENT SCORE (OUT of 50) + Domain Specific SCORE (OUT 50)
5. Create a new column called PERFORMANCE CATEGORY:
   - Excellent: total score >= 90
   - Good: total score >= 75
   - Average: total score < 75
6. Output the cleaned and transformed dataset.

In [ ]:
import os
os.environ["GROQ_API_KEY"] = "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"

In [ ]:
prompt = f"""
You are a data engineer.
Generate technical documentation for the following pipeline:

{pipeline_code}

Include:
- Purpose
- Input data
- Transformation logic
- Output
"""

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

documentation = response.choices[0].message.content
print(documentation)

**Student Academic Evaluation Pipeline Documentation**

**Purpose**

This pipeline is designed to load, clean, and transform student academic evaluation data from a CSV file. The pipeline will remove rows with missing score columns, convert score columns to numeric format, recalculate total score, and create a new column for performance category.

**Input Data**

* **Dataset:** student_evaluation_data.csv
* **Columns:**
	+ NAME OF THE STUDENT
	+ UNIVERSITY
	+ PROGRAM NAME
	+ Specialisation
	+ SEMESTER
	+ Domain
	+ GENERAL MANAGEMENT SCORE (OUT of 50)
	+ Domain Specific SCORE (OUT 50)
	+ TOTAL SCORE (OUT of 100)
	+ RANK
	+ PERCENTILE

**Transformation Logic**

1. **Load CSV Dataset**
	* Read the CSV file using pandas: `pd.read_csv('student_evaluation_data.csv')`
2. **Remove Rows with Missing Critical Score Columns**
	* Filter out rows where either `GENERAL MANAGEMENT SCORE (OUT of 50)` or `Domain Specific SCORE (OUT 50)` is missing using pandas `dropna` function:
	```python
dataset = dataset.dropna(subset=['GENERAL MANAGEMENT SCORE (OUT of 50)', 'Domain Specific SCORE (OUT 50)'])
```
3. **Convert Score Columns to Numeric Format**
	* Convert `GENERAL MANAGEMENT SCORE (OUT of 50)` and `Domain Specific SCORE (OUT 50)` columns to numeric format using pandas `astype` function:
	```python
dataset['GENERAL MANAGEMENT SCORE (OUT of 50)'] = dataset['GENERAL MANAGEMENT SCORE (OUT of 50)'].astype(int)
dataset['Domain Specific SCORE (OUT 50)'] = dataset['Domain Specific SCORE (OUT 50)'].astype(int)
```
4. **Recalculate Total Score**
	* Calculate the total score by adding `GENERAL MANAGEMENT SCORE (OUT of 50)` and `Domain Specific SCORE (OUT 50)` columns using pandas `map` function:
	```python
dataset['TOTAL SCORE (OUT of 100)'] = (dataset['GENERAL MANAGEMENT SCORE (OUT of 50)'] + dataset['Domain Specific SCORE (OUT 50)']).astype(int)
```
5. **Create Performance Category Column**
	* Create a new column called `PERFORMANCE CATEGORY` using pandas `numpy.where` function:
	```python
import numpy as np

dataset['PERFORMANCE CATEGORY'] = np.where(dataset['TOTAL SCORE (OUT of 100)'] >= 90, 'Excellent',
                                          np.where(dataset['TOTAL SCORE (OUT of 100)'] >= 75, 'Good', 'Average'))
```

**Output**

* **Cleaned and Transformed Dataset:**
	+ **Columns:**
		- `NAME OF THE STUDENT`
		- `UNIVERSITY`
		- `PROGRAM NAME`
		- `Specialisation`
		- `SEMESTER`
		- `Domain`
		- `GENERAL MANAGEMENT SCORE (OUT of 50)`
		- `Domain Specific SCORE (OUT 50)`
		- `TOTAL SCORE (OUT of 100)`
		- `PERFORMANCE CATEGORY`
	+ **Data Type:** Pandas DataFrame
	+ **Format:** CSV file

**Pipeline Code:**
```python
import pandas as pd
import numpy as np

def load_dataset(file_path):
    return pd.read_csv(file_path)

def remove_missing_scores(dataset):
    return dataset.dropna(subset=['GENERAL MANAGEMENT SCORE (OUT of 50)', 'Domain Specific SCORE (OUT 50)'])

def convert_score_columns(dataset):
    dataset['GENERAL MANAGEMENT SCORE (OUT of 50)'] = dataset['GENERAL MANAGEMENT SCORE (OUT of 50)'].astype(int)
    dataset['Domain Specific SCORE (OUT 50)'] = dataset['Domain Specific SCORE (OUT 50)'].astype(int)
    return dataset

def recalculate_total_score(dataset):
    dataset['TOTAL SCORE (OUT of 100)'] = (dataset['GENERAL MANAGEMENT SCORE (OUT of 50)'] + dataset['Domain Specific SCORE (OUT 50)']).astype(int)
    return dataset

def create_performance_category(dataset):
    dataset['PERFORMANCE CATEGORY'] = np.where(dataset['TOTAL SCORE (OUT of 100)'] >= 90, 'Excellent',
                                                np.where(dataset['TOTAL SCORE (OUT of 100)'] >= 75, 'Good', 'Average'))
    return dataset

def pipeline(file_path):
    dataset = load_dataset(file_path)
    dataset = remove_missing_scores(dataset)
    dataset = convert_score_columns(dataset)
    dataset = recalculate_total_score(dataset)
    dataset = create_performance_category(dataset)
    return dataset

file_path = 'student_evaluation_data.csv'
output_dataset = pipeline(file_path)
output_dataset.to_csv('output_data.csv', index=False)
```

In [ ]:
question = "Explain the transformation logic of this pipeline in simple terms.in telugu under 10 lines"

chat_prompt = f"""
You are a helpful data engineer assistant.

Here is the pipeline documentation:
{documentation}

Answer the following question clearly and concisely:
{question}
"""

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {"role": "user", "content": chat_prompt}
    ]
)

answer = response.choices[0].message.content
print(answer)

ఈ పైపులైన్ తరంగం లాగా మార్చు దిద్దుబాటు జ్ఞానం.

1. మనం ఇన్‌పుట్ ఫైల్‌ని చదవాలి. (తెలుగు నంబర్లు మరియు నామమాత్రం సంఖ్యలు వేరు చెబిస్తుంది.)
2. మిగిలిన సంభావ్య నకరాత్మక విలువలను నిష్క్రమించండి.
3. వివరణాత్మక గుణకాలను సంఖ్య రూపంలోకి మార్చండి.
4. మొత్తం గుణకం కోసం కొత్త వర్గం లను కలిపి.
5. చివరగా, సాధన విభాగంలో జ్యామితిలో అర్హతలు కల్పించండి.

In [ ]:
runbook_prompt = f"""
You are a data engineer responsible for operating this data pipeline.

Based on the pipeline described below, generate an operational runbook.

Pipeline description:
{pipeline_code}

The runbook must include:
1. Prerequisites (software, libraries, files needed)
2. Steps to run the pipeline
3. Common failure scenarios
4. How to troubleshoot and recover from failures

Do not invent columns or tools that are not mentioned.
"""

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {"role": "user", "content": runbook_prompt}
    ]
)

runbook = response.choices[0].message.content
print(runbook)

**Operational Runbook: Student Academic Evaluation Pipeline**

**Version:** 1.0

**Prerequisites:**

1. **Software:** Python 3.9 or later installed on the machine.
2. **Libraries:**
	* `pandas` for data manipulation and analysis.
	* `numpy` for numerical computations.
3. **Files:**
	* `student_evaluation.csv`: the dataset containing student academic evaluation details.
	* `transformations.py`: a Python script containing the pipeline logic.

**Steps to Run the Pipeline:**

1. **Load prerequisites:** Ensure Python, pandas, and numpy are installed. Also, verify that `student_evaluation.csv` is in the correct location.
2. **Run the pipeline:** Execute the `transformations.py` script using Python: `python transformations.py`
3. **Monitor pipeline execution:** Observe the output of the pipeline, which should be stored in a transformed dataset.

**transformations.py:**
```python
import pandas as pd
import numpy as np

# Load dataset
def load_dataset(file_path):
    return pd.read_csv(file_path)

# Remove rows with missing critical score columns
def remove_missing_scores(df):
    return df.dropna(subset=['GENERAL MANAGEMENT SCORE (OUT of 50)', 'Domain Specific SCORE (OUT 50)'])

# Convert score columns to numeric format
def convert_scores_to_numeric(df):
    df['GENERAL MANAGEMENT SCORE (OUT of 50)'] = pd.to_numeric(df['GENERAL MANAGEMENT SCORE (OUT of 50)'])
    df['Domain Specific SCORE (OUT 50)'] = pd.to_numeric(df['Domain Specific SCORE (OUT 50)'])
    return df

# Recalculate total score
def recalculate_total_score(df):
    df['TOTAL SCORE (OUT of 100)'] = df['GENERAL MANAGEMENT SCORE (OUT of 50)'] + df['Domain Specific SCORE (OUT 50)']
    return df

# Create PERFORMANCE CATEGORY column
def create_performance_category(df):
    df['PERFORMANCE CATEGORY'] = np.select([df['TOTAL SCORE (OUT of 100)'] >= 90, df['TOTAL SCORE (OUT of 100)'] >= 75, df['TOTAL SCORE (OUT of 100)'] < 75], ['Excellent', 'Good', 'Average'])
    return df

# Output transformed dataset
def output_transformed_dataset(df):
    print(df)

# Main pipeline function
def pipeline(file_path):
    df = load_dataset(file_path)
    df = remove_missing_scores(df)
    df = convert_scores_to_numeric(df)
    df = recalculate_total_score(df)
    df = create_performance_category(df)
    output_transformed_dataset(df)

# Run the pipeline
if __name__ == '__main__':
    pipeline('student_evaluation.csv')
```

**Common Failure Scenarios:**

1. **Dataset loading issues:** If the dataset is corrupted or incorrectly formatted.
2. **Missing critical score columns:** If rows with missing scores are not handled properly.
3. **Data type conversion errors:** If score columns cannot be converted to numeric format.

**Troubleshooting and Recovery:**

1. **Dataset loading issues:**
	* Verify the dataset file exists and is in the correct location.
	* Check the dataset for corrupt or incorrectly formatted data.
2. **Missing critical score columns:**
	* Check the `remove_missing_scores` function to ensure it is correctly handling missing scores.
	* Verify that the `dropna` function is being applied correctly.
3. **Data type conversion errors:**
	* Verify that the `convert_scores_to_numeric` function is correctly applying the `pd.to_numeric` method.
	* Check the score columns to ensure they contain data that can be converted to numeric format.

**Recovery:** Run the pipeline with error handling or debug the code to identify and fix the root cause of the issue.

**Example Use Case:**

Assume we have a CSV file `student_evaluation.csv` containing the following data:
```csv
NAME OF THE STUDENT,UNIVERSITY,PROGRAM NAME,SPECIALISATION,SEMESTER,DOMAIN,GENERAL MANAGEMENT SCORE (OUT of 50),Domain Specific SCORE (OUT 50),TOTAL SCORE (OUT of 100),RANK,PERCENTILE
John Smith,University X,Program Y,Specialization A,1,Math,40,30,70,1,90
Jane Doe,University Z,Program A,Specialization B,2,Science,50,40,90,2,95
```
 Running the pipeline with this dataset produces the transformed output:
```csv
NAME OF THE STUDENT,UNIVERSITY,PROGRAM NAME,SPECIALISATION,SEMESTER,DOMAIN,GENERAL MANAGEMENT SCORE (OUT of 50),Domain Specific SCORE (OUT 50),TOTAL SCORE (OUT of 100),RANK,PERCENTILE,PERFORMANCE CATEGORY
John Smith,University X,Program Y,Specialization A,1,Math,40,30,70,1,90,Good
Jane Doe,University Z,Program A,Specialization B,2,Science,50,40,90,2,95,Excellent
```